In [1]:
# Create a vector
v <- c(5, 10, 15, 20, 25)
print(v)

[1]  5 10 15 20 25


In [2]:
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [3]:
m[2, 3]

[1] 6

In [4]:
m[1, 2] <- 99
print(m)


     [,1] [,2] [,3]
[1,]    1   99    5
[2,]    2    4    6


In [5]:
a <- matrix(c(1, 2, 3, 4), nrow=2)
b <- matrix(c(2, 0, 1, 3), nrow=2)

result <- a %*% b
print(result)


     [,1] [,2]
[1,]    2   10
[2,]    4   14


In [6]:
# Create a 5x3 matrix: [CO2, Temp Anomaly, Deforestation Rate]
climate <- matrix(c(
  9.2, 1.1, 0.8,   # Country A
  6.5, 0.9, 1.2,   # Country B
  2.3, 0.7, 2.5,   # Country C
  3.8, 1.0, 1.5,   # Country D
  7.1, 1.2, 0.9    # Country E
), nrow=5, byrow=TRUE)

colnames(climate) <- c("CO2", "Temp", "Deforestation")
rownames(climate) <- c("A", "B", "C", "D", "E")

print(climate)

  CO2 Temp Deforestation
A 9.2  1.1           0.8
B 6.5  0.9           1.2
C 2.3  0.7           2.5
D 3.8  1.0           1.5
E 7.1  1.2           0.9


In [7]:
scaled_climate <- scale(climate)
print(scaled_climate)

         CO2       Temp Deforestation
A  1.2490573  0.6238503    -0.8487300
B  0.2629594 -0.4159002    -0.2633990
C -1.2709706 -1.4556507     1.6389269
D -0.7231384  0.1039750     0.1755993
E  0.4820923  1.1437255    -0.7023972
attr(,"scaled:center")
          CO2          Temp Deforestation 
         5.78          0.98          1.38 
attr(,"scaled:scale")
          CO2          Temp Deforestation 
    2.7380650     0.1923538     0.6833740 


In [8]:
# Transformation matrix: keep CO2 and Temp, invert Deforestation
flip <- matrix(c(1, 0, 0,
                 0, 1, 0,
                 0, 0, -1), nrow=3)

transformed <- scaled_climate %*% flip
print(transformed)

        [,1]       [,2]       [,3]
A  1.2490573  0.6238503  0.8487300
B  0.2629594 -0.4159002  0.2633990
C -1.2709706 -1.4556507 -1.6389269
D -0.7231384  0.1039750 -0.1755993
E  0.4820923  1.1437255  0.7023972


In [9]:
transposed <- t(transformed)
print(transposed)


             A          B         C          D         E
[1,] 1.2490573  0.2629594 -1.270971 -0.7231384 0.4820923
[2,] 0.6238503 -0.4159002 -1.455651  0.1039750 1.1437255
[3,] 0.8487300  0.2633990 -1.638927 -0.1755993 0.7023972


In [10]:
# Example: double the CO2 contribution
weight <- matrix(c(2, 0, 0,
                   0, 1, 0,
                   0, 0, -1), nrow=3)

adjusted <- scaled_climate %*% weight
print(adjusted)

        [,1]       [,2]       [,3]
A  2.4981145  0.6238503  0.8487300
B  0.5259188 -0.4159002  0.2633990
C -2.5419411 -1.4556507 -1.6389269
D -1.4462768  0.1039750 -0.1755993
E  0.9641846  1.1437255  0.7023972
